[package]
name        = "aktoro"
description = "Yet another actor framework for Rust."
version     = "0.0.0"
license     = "MIT"
authors     = ["Matthieu Le Brazidec <matthieu@lebrazidec.email>"]
edition     = "2018"

[workspace]
members = [
	".",
	"aktoro-channel",
	"aktoro-raw",
]
