[package]
name    = "aktoro-raw"
version = "0.0.0"
license = "MIT"
authors = ["Matthieu Le Brazidec <matthieu@lebrazidec.email>"]
edition = "2018"

[dependencies]
futures-core-preview = "0.3.0-alpha.16"
